---
##################################################################
# This playbok is designed to be ran from a jenkins pipeline
# and assumes all associated files have been checked out
# from a git repo during the 'checkout' stage
#################################################################

- name: Install and ensure Apache is running 
  hosts: servers
  become: true          
  gather_facts: true

  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: true

    - name: Ensure Apache is started and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
